### ISSUE TITLE
hoping support latest .netcore,otherwise unable to use with latest deep learning framework,such as latest tensorflow.net,torchsharp, etc

### ISSUE THREAD

**Issue by xinheblue** [jmp75/rdotnet#145]
Hoping providing support!

Best regards,

**Comment by lrasmus** [comment]
Are you experiencing any problems with the latest .NET Core?  I am not aware (or rather, I haven't heard of) any specific problems related to the version of .NET Core.

**Comment by xinheblue** [comment]
> Are you experiencing any problems with the latest .NET Core? I am not aware (or rather, I haven't heard of) any specific problems related to the version of .NET Core.

Thank you for your reply!

We find that under netcore3/netcore5  environment, we are not be able to get the instance of REngine, it will crash in the following codes

 REngine engine = REngine.GetInstance();
 engine.Initialize();

Tested for the master and netcore5 branch, all with the same issue.

it seems that the problem happens on the depended DynamicInterop.

Hoping providing support, best regards!

**Comment by lrasmus** [comment]
Ah!  Thanks so much for the additional info.  What version of R are you running?  We've had a lot of reports and discussion in issue #139 that's tied to R 4.0.3 or higher.  I'm not sure if you can use R 4.0.2, otherwise I have [just posted a workaround](https://github.com/rdotnet/rdotnet/issues/139#issuecomment-904294759) that may address the issue for now.

**Comment by xinheblue** [comment]
> Ah! Thanks so much for the additional info. What version of R are you running? We've had a lot of reports and discussion in issue #139 that's tied to R 4.0.3 or higher. I'm not sure if you can use R 4.0.2, otherwise I have [just posted a workaround](https://github.com/rdotnet/rdotnet/issues/139#issuecomment-904294759) that may address the issue for now.

Thank you for your reply, you helped us a lot!

For details, we find
R 4.10.0 + netcore5, crash
R 4.0.2 + netcore5, not crash
R 4.10.0 + net framework, not crash

Best regardsd!

**Comment by lrasmus** [comment]
Glad you were able to workaround it, and thanks again for the helpful reporting!  I'll let @jmp75 close this issue, since it seems like you've got a solution for now.  We'll keep tracking progress on the R 4.0.3 fixes in #139.
