### ISSUE TITLE
Error: package or namespace load failed for ‘lintr’:

### ISSUE THREAD

**Issue by NM-peterdavey** [jmp75/rdotnet#155]
Using R version 3.6.1.

> install.packages("lintr",lib="/home/peter/R_personal_lib", dependencies = TRUE)

> library("lintr")
Error: package or namespace load failed for ‘lintr’:
 object ‘R_user_dir’ is not exported by 'namespace:backports'

Any idea why lintr is not loading correctly?

Many thanks.

**Comment by mikeparanoid** [comment]
how did you resolve this?
