### ISSUE TITLE
Do not crash when R_Visible does not exist

### ISSUE THREAD

**Issue by tpetricek** [jmp75/rdotnet#17]
As discussed in https://github.com/BlueMountainCapital/FSharpRProvider/pull/152, in the `GetVisible` method, we have the following:

    var symbol = DangerousGetHandle("R_Visible");
    var value = Marshal.ReadInt32(symbol);
    var result = Convert.ToBoolean(value);
    return result;

With my version of R, the first call returns 0 and we get a nice access violation exception reading from the address 0 :-). PR with a fix coming soon!

**Comment by jmp75** [comment]
I see. While R version 3.x has been around for a while, probably wise to support 2.x if easy to do indeed. Thanks for this. I need to set up a CI, and I'll keep in mind the possibility to test several versions of R. Let me know if you need a re-release soon-ish.

**Comment by tpetricek** [comment]
No problem, I'm happy to test things on 2.x when integrating recent versions into BMC codebase. I think they should update :-).

Having a release soonish would be nice (because there is a whole chain of releases that I need to do before the new R.NET makes it into FsLab).

**Comment by tpetricek** [comment]
Also, thanks a lot for all the improvements in R.NET and for helping us integrate those into R provider. It makes such a compelling case for type providers and it would never work without R.NET!

**Comment by jmp75** [comment]
I have pushed 1.6.4 packages to nuget.
