### ISSUE TITLE
unable to evaluate histogram: Evaluation Exception

### ISSUE THREAD

**Issue by buddalasunil999** [jmp75/rdotnet#23]
When I try to evaluate something like below I'm getting an exception. Could someone help me solve this problem.

hist(c(1,2,1,3,4,2,3,1,2,3,4,1,2,3,4,2,5,3,2,1,2,4,5,2,3,4,5,1,2,3,1,2,4,2,1,2))

I am getting the below error

Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Program Files/R/R-3.2.2/library/stats/libs/i386/stats.dll':
  LoadLibrary failure:  The specified module could not be found.

**Comment by skyguy94** [comment]
How are you running this? That error usually happens if you are running under IIS in an ASP.Net application. The workaround is to make sure the R appropriate bin folder is on your path (and restart IIS so that it picks up the path change) so that dll resolution can find the appropriate dlls.

**Comment by buddalasunil999** [comment]
Yes, I'm running under IIS in an ASP.NET application. There are other things working but I see only problem with hist. My path already contains bin of R. So it must be something else that's wrong in it.
When I just evaluate hist(c(1:4)) it works. But for some hist data it's not working. It's so annoying I'm not able to figure out what's going wrong.

**Comment by skyguy94** [comment]
You haven't provided any sort of evidence that you have a unique problem. Before dismissing my suggestion, I suggest you look at this issue thread (https://rdotnet.codeplex.com/workitem/117), make sure that the appropriate bin folder is on your path, restart IIS, and try again.

**Comment by buddalasunil999** [comment]
Oh sorry, I'll cross check again tomorrow. I can't access the work now. I was sure I added R bin to path because I was executing R script from command prompt. Thanks for your response.

-----Original Message-----

**Comment by skyguy94** [comment]
No worries. Let me know what you find out.

**Comment by buddalasunil999** [comment]
It's working

**Comment by skyguy94** [comment]
Outstanding. Glad its working now.
