### ISSUE TITLE
RDotNet and R version 3.2.4

### ISSUE THREAD

**Issue by makillamasoft** [jmp75/rdotnet#32]
Has anyone else upgraded to R-3.2.4revised-win yet?

I'm getting an error when trying to SetEnvironmentVariables

REngine.SetEnvironmentVariables();

rCurrentVersionString from registry is coming back as "3.2.4 revised"

return new Version(rCurrentVersionStringFromRegistry); throwing system.format exception.

Any suggestions on a fix?

**Comment by nofuture-git** [comment]
encountered this too:  this should fix it 
`return new Version(string.Join(string.Empty,
                (version ?? new Version().ToString()).ToCharArray().Where(s => IsDigit(s) || Equals(s, '.'))));`

**Comment by makillamasoft** [comment]
Updating R to 3.2.5 (current version) bypasses this issue.
