### ISSUE TITLE
RDotNet signed DLLs  running on x64

### ISSUE THREAD

**Issue by mrockwell** [jmp75/rdotnet#37]
I am trying to deploy RDotNet with my x64 project which uses signed DLLs. I was able to successfully sign the RDotNet dll so that my project ran but, when running i started getting an error saying DynamicInterop needed to be signed. Applied same steps as with RDotNet signing to sign DynamicInerop and now get the following error:

error CS0012: The type 'DynamicInterop.UnmanagedDll' is defined in an assembly that is not referenced. You must add a reference to assembly 'DynamicInterop, Version=0.7.4.0, Culture=neutral, PublicKeyToken=null'

The newly signed DynamicInterop is referenced in my project and copied to my run folder. Any ideas? appreciate any and all help. Thanks.

**Comment by makillamasoft** [comment]
There should be 3 dlls you will need to sign and included in your projects references IIRC.
RDotNet
RdotNet.NativeLibrary
and DynamicInterop

**Comment by mrockwell** [comment]
Thanks so much for taking the time to reply, really appreciate the help. I have now signed all three dlls and verified that they were indeed properly signed. Now, when i build, i get this error:

 error CS0012: The type 'DynamicInterop.UnmanagedDll' is defined in an assembly that is not referenced. You must add a reference to assembly 'DynamicInterop, Version=0.7.4.0, Culture=neutral, PublicKeyToken=null'.

when i run the command:

sn -T RDotNet.dll 

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.33440
Copyright (c) Microsoft Corporation.  All rights reserved.

Public key token is 864f2e39d66a1e2d

so seems to me that even though rdotnet.dll is now signed internally it is still referencing the unsigned version of dynamicinterop. Any way you guys can provide signed versions of these dlls? Thanks again for the help.

**Comment by mrockwell** [comment]
sorry, issue still opened, clicked the wrong button.

**Comment by makillamasoft** [comment]
Did you check the references in your project/solution?
I'm going to hazard a guess that the path to the dll is to the old unsigned one.
I'd remove the reference and then re-add it and recompile.
It might solve your issue.

**Comment by mrockwell** [comment]
Tried that and no, it doesn't solve the problem. Remember that rdotnet was
originally built using the unsigned dll so even after I sign the dll
internally it is still going to want to load the unsigned version because
that's what it was built with. Seems only path forward is for me to attempt
to build the solution and sign the dlls myself or have them provided to me
from your side, latter definitely preferred. Surprised this hasn't come up
before. Please consider providing a signed release build of these dlls.
Thanks.

On Wednesday, April 27, 2016, makillamasoft <notifications@github.com>
wrote:

> Did you check the references in your project/solution?
> I'm going to hazard a guess that the path to the dll is to the old
> unsigned one.
> I'd remove the reference and then re-add it and recompile.
> It might solve your issue.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/jmp75/rdotnet/issues/37#issuecomment-215066112>
>


-- 
-- 
Marcus Rockwell
President

Rockwell IT Services, Inc.
9801 Westheimer Suite 302
Houston, TX 77042
281-385-9025

www.rockwellits.com

Sent from my iPad

**Comment by makillamasoft** [comment]
Ahh, somehow I was assuming that you were going to be signing the dlls yourself.
I'm not part of the team working on this project. Just a dev. leveraging the teams work.

I believe that they can not sign the dlls as it's being used in another project.
see the discussion:
http://rdotnet.codeplex.com/discussions/546687

**Comment by mrockwell** [comment]
I am very new to github and git cvs, mind sharing with me how i can go about downloading the project and building it myself or pointing me to some docs that describe how downloading and building the code yourself is accomplished. thanks.

**Comment by makillamasoft** [comment]
http://jmp75.github.io/rdotnet/getting_started/
