### ISSUE TITLE
Rnning c# application in a machine that don't have R installed in

### ISSUE THREAD

**Issue by Nadjib23** [jmp75/rdotnet#58]
Hi,
I have an R script that i want to use from C#, so i must have R installed in my developpement machine, but the question is, will it work if i use this application in an other machine that haven't R installed in it.

**Comment by dannyparsons** [comment]
No, it won't work. RDotNet just allows you to connect to R if it is installed on the machine running the application. If the machine does not have R installed, then RDotNet cannot run an R script.

**Comment by Nadjib23** [comment]
Okay, thanks for your answer
