### ISSUE TITLE
RDotNet.Graphics.Tests: the program class runs into NullReferenceException

### ISSUE THREAD

**Issue by Novalis83** [jmp75/rdotnet#72]
Guys, 
I'm trying to run Program.cs in RDotNet.Graphics.Test project without success. The aforementioned exception occurs when the flow calls the method DrawCircle in GraphicsDeviceAdapter.cs file. Here the input parameter IntPtr gc is 0. I write the code down:

` private void DrawCircle(double x, double y, double r, IntPtr gc /* gc is equal to zero */, IntPtr dd)
        {
            var context = new GraphicsContext(gc); // context cannot be initialized properly
            var center = new Point(x, y);
            this.device.DrawCircle(center, r, context, this.description);
        }`

Can anyone help me on this issue? Does it work for you? 

Thanks so much!

**Comment by jmp75** [comment]
@Novalis83, I have not looked at 'graphics' related assemblies and they should be discontinued. R.NET is moving towards .NET core 2.1 support and winforms is not part of this. Other contributors and I are focusing on .NET core support and adapting to significant changes in R 3.5 and are unlikely to look at winforms/graphics interop support.

**Comment by GeorgeS2019** [comment]
@jmp75 please comment what will happen to graphics milestone. :NETCore 3, 5 and upcoming 6 provide WinForm support.
