### ISSUE TITLE
R home directory is not defined

### ISSUE THREAD

**Issue by felipecruz91** [jmp75/rdotnet#77]
Hi,

I am running a .NET Core 2.0 Web API within a **linux** Docker container. This API uses the `R.NET (1.7.0)` NuGet package.

When debugging, it crashes in line number 182:

![image](https://user-images.githubusercontent.com/15997951/39959433-ce852846-5611-11e8-94b7-6a5d919c07dd.png)

`Fatal error: R home directory is not defined`
`The program '[211] dotnet' has exited with code 0 (0x0).`
`The program '' has exited with code 0 (0x0).`

This is very weird as if I get inside the docker container by `docker exec -it {containerID} bash`  and execute `which R` I get the path where the `R` executable is installed: `/usr/bin/R`.

Therefore, I am able to execute R scripts manually within the container, but I am not through the `R.NET` library.

![image](https://user-images.githubusercontent.com/15997951/39959511-fd7339a8-5612-11e8-8933-d76766b5802d.png)

Has anyone faced this issue before?

**Comment by felipecruz91** [comment]
Despite the fact I was setting the `R_HOME` environment variable via:
`REngine.SetEnvironmentVariables(rPath, rHomePath);` , **the** `R_HOME` **env. variable never got set**.
I reckon this is a bug and should be fixed.

The solution was to add the following line in my Dockerfile:

`ENV R_HOME /usr/lib/R`

**Comment by laloutre87** [comment]
I get the same error now with version 1.8.2. 

REngine.SetEnvironmentVariables doesn't change anything.
Calling  Environment.SetEnvironmentVariable("R_HOME", "/usr/lib/R");    before   doesn't change  anything.

And passing RHome = "/usr/lib/R"   in StartupParameter  raise 
System.NotSupportedException: Specified method is not supported. at RDotNet.StartupParameter.set_RHome(String value)

Web app running on kestrel .net core 3.1

**Comment by miemengniao** [comment]
in net8， my workaround like below:

// in my docker file
RUN apt-get update && apt-get install -y \
    libc6-dev

RUN ln -s /lib/x86_64-linux-gnu/libdl.so.2 /lib/libdl.so
RUN R_HOME="/usr/lib/R"
RUN export R_HOME
ENV R_HOME /usr/lib/R


// in the init code
 Environment.SetEnvironmentVariable("R_HOME", "/usr/lib/R"); // I am not sure where it useful
 REngine.SetEnvironmentVariables("/usr/lib/R", "usr/lib/R");
