### ISSUE TITLE
R.NET license

### ISSUE THREAD

**Issue by diegocorradini** [jmp75/rdotnet#81]
Hi,

I am using your library, which I find very useful btw. 
May I ask you a clarification about the license? 
I see from nuget website that the license of R.NET is BSD. However R is under GPL, therefore which kind of license will have my application? 

I am using only some R scritps without importing any other packages.

Best Regards

**Comment by CSharpDummy** [comment]
Same here ... without MIT license, you cant use the software in any commercial product.

**Comment by jmp75** [comment]
[R.NET 1.8.1](https://www.nuget.org/packages/R.NET/1.8.1) is now under MIT.
